# Generated by Django 4.2.16 on 2026-01-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plastic', 'Plastic'), ('fashion', 'Fashion'), ('transport', 'Transport')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_coastal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_count', models.PositiveIntegerField(default=1)),
                ('income_bracket', models.CharField(choices=[('low', 'Low'), ('mid', 'Middle'), ('high', 'High')], max_length=20)),
                ('diet_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non Vegetarian'), ('fish', 'Fish-heavy')], default='nonveg', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locationcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitytype')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.householdprofile')),
            ],
        ),
    ]
