# Generated by Django 4.2.16 on 2026-01-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('plastic_score', models.FloatField(default=50)),
                ('fashion_score', models.FloatField(default=50)),
                ('transport_score', models.FloatField(default=50)),
                ('overall_score', models.FloatField(default=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.householdprofile')),
            ],
        ),
    ]
